"""add Department

Revision ID: 3669a33736e5
Revises: 4bae9d4abdf1
Create Date: 2024-10-03 06:12:50.028424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3669a33736e5'
down_revision = '4bae9d4abdf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
